package com.oscar.sanchez.tqs1.Selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestSeleniumTest extends Object {
    WebDriver driver;
    Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:/WebDriver/bin/geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testSelenium() {
        driver.get("http://tqs1.herokuapp.com/");
        driver.manage().window().setSize(new Dimension(550, 697));
        driver.findElement(By.linkText("Form")).click();
        driver.findElement(By.name("city")).click();
        driver.findElement(By.name("city")).sendKeys("Madrid");
        driver.findElement(By.cssSelector(".input-group-text")).click();
        assertThat(driver.findElement(By.id("cityName")).getText(), is("Madrid"));
    }
    @Test
    public void testErrorPage() {
        driver.get("http://tqs1.herokuapp.com/");
        driver.manage().window().setSize(new Dimension(550, 697));
        driver.findElement(By.linkText("Form")).click();
        driver.findElement(By.name("city")).click();
        driver.findElement(By.name("city")).sendKeys("Coslada");
        driver.findElement(By.cssSelector(".input-group-text")).click();
        assertThat(driver.getTitle(), is ("ERROR"));
    }
}
